import os
import shutil
import subprocess
import tempfile
from backend.utils.config import settings
from backend.utils.logger import logger

def convert_dxf_to_dwg(dxf_path: str, output_dwg_path: str) -> str:
    """
    Converts a DXF file to a DWG file using the ODA File Converter.
    Wraps the process execution using temporary directories since ODA Converter
    operates on directory level rather than file level.
    """
    logger.info(f"Attempting to convert DXF to DWG: {dxf_path}")
    
    converter_path = settings.ODA_CONVERTER_PATH
    
    # Check if converter executable exists
    # If not, raise an error so the service can log and fallback to DXF download
    if not os.path.exists(converter_path) and not shutil.which(os.path.basename(converter_path)):
        logger.warning(
            f"ODA File Converter executable not found at '{converter_path}' or in system PATH. "
            "DWG conversion will be skipped. Only DXF will be available."
        )
        raise FileNotFoundError(f"ODA File Converter not found. Path: {converter_path}")
        
    # Create workspace-safe temp folders
    # Sandbox requires all temporary creation to be inside the workspace
    workspace_temp_base = os.path.join(settings.UPLOAD_DIR, "temp_dwg_conv")
    os.makedirs(workspace_temp_base, exist_ok=True)
    
    # Subdirectories for this run
    temp_dir_in = tempfile.mkdtemp(dir=workspace_temp_base)
    temp_dir_out = tempfile.mkdtemp(dir=workspace_temp_base)
    
    try:
        # Copy DXF to temp input directory
        dxf_filename = os.path.basename(dxf_path)
        shutil.copy(dxf_path, os.path.join(temp_dir_in, dxf_filename))
        
        # Run ODA Converter Command:
        # ODAFileConverter.exe [Input Folder] [Output Folder] [Input Version] [Output Format] [Recurse] [Audit] [Filter]
        # Target DWG version: ACAD2010 (R2010) matching our ezdxf output version
        cmd = [
            converter_path,
            temp_dir_in,
            temp_dir_out,
            "ACAD2010",
            "DWG",
            "0", # recurse (0 = false)
            "1"  # audit (1 = true)
        ]
        
        logger.info(f"Running ODA File Converter command: {' '.join(cmd)}")
        result = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=30 # 30 seconds max
        )
        
        if result.returncode != 0:
            logger.error(f"ODA Converter returned error code {result.returncode}. Stderr: {result.stderr}")
            raise RuntimeError(f"ODA Converter failed: {result.stderr or result.stdout}")
            
        # Find output DWG file in the output folder
        dwg_filename = os.path.splitext(dxf_filename)[0] + ".dwg"
        generated_dwg = os.path.join(temp_dir_out, dwg_filename)
        
        if not os.path.exists(generated_dwg):
            # Sometimes ODA converter does not output errors but files are missing
            logger.error(f"ODA Converter ran, but output file is missing at: {generated_dwg}. Command output: {result.stdout}")
            raise FileNotFoundError("DWG file was not generated by ODA Converter.")
            
        # Move the generated file to final destination
        os.makedirs(os.path.dirname(output_dwg_path), exist_ok=True)
        shutil.move(generated_dwg, output_dwg_path)
        logger.info(f"Successfully converted and saved DWG to: {output_dwg_path}")
        return output_dwg_path
        
    except Exception as e:
        logger.error(f"Error during DXF to DWG conversion: {e}")
        raise e
        
    finally:
        # Clean up temp folders
        try:
            shutil.rmtree(temp_dir_in, ignore_errors=True)
            shutil.rmtree(temp_dir_out, ignore_errors=True)
        except Exception as cleanup_err:
            logger.warning(f"Failed to clean up temp directories: {cleanup_err}")
